esports_port_thailand/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('team/', include('team.urls')),
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout')
    # path('member/', include('django.contrib.auth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

member/urls.py
# from django.urls import path
from django.conf.urls import url , include
from django.urls import path
from . import views

app_name = 'member'
urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/post/<int:pk>/delete/',views.DeletePost.as_view(), name='delete_post'),
    path('player/<int:pk>/',views.Player.as_view(),name='player'),
    path('player/<int:pk>/follow/',views.Following.as_view(),name='following'),
    path('player/<int:pk>/unfollow/',views.Unfollow.as_view(),name='unfollow'),
    path('profile/',views.Profile.as_view(),name='profile'),
    path('profile/<int:pk>/edit/',views.EditProfile.as_view(),name='edit_profile'),
    path('mail/',views.MailBox.as_view(),name='mail'),
    path('mail/send/',views.SendMail.as_view(),name='send_mail'),
    path('mail/<int:pk>/',views.MailDetail.as_view(),name='mail_detail'),
    path('mail/<int:pk>/delete/',views.DeleteMail.as_view(),name='delete_mail'),
    path('search/',views.FilterUser.as_view(),name='member_search')
]

team/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = "team"
urlpatterns = [
    # path('signup/', views.SignUp.as_view(), name='signup'),
    # url(r'^$',views.index,name='index'),
    # url(r'^login$',views.login,name='login'),
    # url(r'^signup$',views.signup,name='signup'),
    path('', views.Teami.as_view(), name='teami'),
    path('team_info/<int:pk>/', views.TeamInfo.as_view(), name='team_info'),
    url(r'^team_create$', views.CreateTeam.as_view(), name='team_create'),
    url(r'^team_manage$', views.team_manage, name='team_manage'),
    path('team_info/<int:pk>/edit_info/', views.EditInfo.as_view(), name='team_editinfo'),
    url(r'^team_list$', views.team_list, name='team_list'),
    # url(r'^team_recruitment$', views.team_recruitment.as_view(), name='team_recruitment'),
    # url(r'^team_recruitment_list$', views.team_recruitment_list.as_view(), name='team_recruitment_list'),
    path('team_recruitment_list/',views.team_recruitment_list.as_view(),name='team_recruitment_list'),
    path('team_recruitment_list/<int:pk>/',views.team_recruitment.as_view(),name='team_recruitment'),
    url(r'^team_recruitment_create$', views.team_recruitment_create.as_view(), name='team_recruitment_create'),
    path('search/',views.FilterTeam.as_view(),name="team_search")
    # url(r'^profile$',views.profile,name='profile'),
    # path('home/',views.signup),
    # path('<code_name>/',views.profile)
]

team/models.py
from django.db import models
from django.contrib.auth.models import User
from member.models import Game

class Team(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    website = models.URLField(blank=True)
    description = models.CharField(max_length=100,blank=True)
    founder = models.OneToOneField(User,models.SET_NULL,blank=True,null=True)
    game = models.ForeignKey(Game,models.SET_NULL,blank=True,null=True)
    img = models.ImageField(default='default/default_team.png',blank=True)
    class Meta:
        unique_together = (("game", "name"))

    def __str__(self):
        return self.name + " - " + self.game.name

class TeamRole(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class TeamMember(models.Model):
    team = models.ForeignKey(Team,on_delete=models.CASCADE)
    member = models.ForeignKey(User,on_delete=models.CASCADE)
    role = models.ForeignKey(TeamRole,models.SET_NULL,null=True)
    join_date = models.DateField(auto_now_add=True)
    class Meta:
        unique_together = (("team","member"))
    def __str__(self):
        return  self.member.username + " - " + self.team.name + " - " + self.role.name

class TeamRecruitPost(models.Model):
    # recruit_id = models.CharField(max_length=4)
    id = models.IntegerField(primary_key=True)
    heading = models.CharField(max_length=50)
    # img_cover = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    start_date = models.DateField(auto_now_add='')
    end_date = models.DateField(auto_now_add='')
    # team_name = models.CharField(max_length=20)

team/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Team,TeamMember,TeamRole,TeamRecruitPost

class CreateTeamForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}))
    class Meta:
        model = Team
        fields = [
            'name',
            'email',
            'website',
            'description',
            'game',
        ]
    def save(self,commit=True):
        team = super(CreateTeamForm, self).save(commit=False)   
        team.name = self.cleaned_data['name']
        team.email = self.cleaned_data['email']
        team.website = self.cleaned_data['website']
        team.description = self.cleaned_data['description']
        team.game = self.cleaned_data['game']
        if commit:
            team.save()
            join_team = TeamMember()
            join_team.member = team.founder
            join_team.team = team
            role = TeamRole.objects.get(name="Player")
            join_team.role = role
            join_team.save()
        
        return team

class EditTeamInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}))
    class Meta:
        model = Team
        fields = [
            'name',
            'email',
            'website',
            'description',
            'game',
            'img'
        ]

class TeamRecruitForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}))
    class Meta:
        
        model = TeamRecruitPost
        fields = [
            'heading',
            'description',
            'start_date',
            'end_date'
        ]
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }
    def save(self,commit=True):
        recruit = super(TeamRecruitForm, self).save(commit=False)
        recruit.heading = self.cleaned_data['heading']
        recruit.description = self.cleaned_data['description']
        if commit:
            recruit.save()
        
        return recruit

team/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .models import Team,TeamMember,TeamRole
from team.forms import CreateTeamForm,EditTeamInfoForm
from django.http import HttpResponseRedirect
from .filters import TeamFilter
from team.forms import TeamRecruitForm
from team.models import TeamRecruitPost
from django.shortcuts import redirect

class Teami(generic.ListView):
    template_name = 'team/teami.html'

    def get_queryset(self):
        return 1

    def dispatch(self,*args,**kwargs):
        member = 0
        try:
            member = TeamMember.objects.get(member=self.request.user)
        except:
            return super(Teami, self).dispatch(*args, **kwargs)
        return HttpResponseRedirect(reverse_lazy('team:team_info',kwargs={'pk': member.team.pk}))
        

class CreateTeam(generic.CreateView):
    form_class = CreateTeamForm
    template_name = 'team/team_create.html'
    model=Team

    def get_success_url(self, *arg, **kwargs):
        team = Team.objects.get(founder=self.request.user)
        return reverse_lazy('team:team_info',kwargs={'pk': team.pk})

    def form_valid(self, form):
        user = self.request.user
        form.instance.founder = user
        return super(CreateTeam, self).form_valid(form)

class TeamInfo(generic.DetailView):
    template_name = 'team/team_info.html'
    model = Team

    def get_context_data(self, **kwargs):
        context = super(TeamInfo,self).get_context_data(**kwargs)
        context['team'] = Team.objects.get(pk=self.kwargs['pk'])
        context['team_member'] = TeamMember.objects.filter(team=context['team'],role=1)
        context['team_manager'] = TeamMember.objects.filter(team=context['team'],role=2)
        context['ck_founder'] = len(Team.objects.filter(founder=self.request.user,pk=self.kwargs['pk']))
        print(context['team_member'])
        return context

class EditInfo(generic.UpdateView):
    model = Team
    template_name = 'team/team_editinfo.html'
    form_class = EditTeamInfoForm

    def get_success_url(self, *arg, **kwargs):
        team = Team.objects.get(founder=self.request.user)
        return reverse_lazy('team:team_info',kwargs={'pk': team.pk})

class FilterTeam(generic.ListView):
    model = Team
    template_name = 'team/team_list.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = TeamFilter(self.request.GET,queryset=self.get_queryset())
        return context

def team_manage(request):
    return render(request, 'team/team_manage.html')

def team_list(request):
    return render(request, 'team/team_list.html')

class team_recruitment(generic.DetailView):
    template_name = 'team/team_recruitment.html'
    model = TeamRecruitPost
    def get_context_data(self, **kwargs):
        context = super(team_recruitment,self).get_context_data(**kwargs)
        context['team_recruitment'] = TeamRecruitPost.objects.get(pk=self.kwargs['pk'])
        return context

    def dispatch(self,*args,**kwargs):
        teamrc = TeamRecruitPost.objects.get(pk=self.kwargs['pk'])
        if self.request.user.pk==teamrc.id:
            return redirect('team:teamrc/<pk>')
        return super(team_recruitment, self).dispatch(*args, **kwargs)


class team_recruitment_list(generic.ListView):
    template_name = 'team/team_recruitment_list.html'
    def get(self,request):
        posts = TeamRecruitPost.objects.all()
        
        args = {'posts':posts}
        return render(request,self.template_name,args)

class team_recruitment_create(generic.CreateView):
    template_name =  'team/team_recruitment_create.html'
    success_url = reverse_lazy('team:team_recruitment_list')
    form_class = TeamRecruitForm

team/templates/team/team_create.html
<style type="text/css">
    .login-box {
        margin: 50px 0px 0px 20px;
        width: 300px;
        max-width: 100%;
    }
</style>
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% block body %}
{% load widget_tweaks %}
<div class="container">
    <div class="login-box">
        <br>
        <form class="controls" method="post">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label_tag }}
                {{ field|add_class:"label input" }}
                {{ field.errors }}
            {% endfor %}
            <br>
            <button class="button" type="submit">Submit</button>
            <button class="button" type="reset">Reset</button>
        </form>
        <br><br><br>
    </div>
</div>
{% endblock %}

team/templates/team/team_editinfo.html
<style type="text/css">
    .login-box {
        margin: 50px 0px 0px 20px;
        width: 300px;
        max-width: 100%;
    }
</style>
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% block body %}
{% load widget_tweaks %}
<div class="container">
    <div class="login-box">
        <h1>Edit Profile</h1>
        <br>
        <form class="controls" method="post">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label_tag }}
                {{ field|add_class:"label input" }}
                {{ field.errors }}
            {% endfor %}
            <br>
            <button class="button" type="submit">Submit</button>
            <button class="button" type="reset">Reset</button>
        </form>
        <br><br><br>
    </div>
</div>
{% endblock %}

team/templates/team/team_info.html
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% block body %}

<div class="container"><br>
    
        <div class="columns is-multiline">
            <div class="column is-one-quarter"><center><img class="image is-128x128" src="{{team.img.url}}" alt="" width="100px;"></center></div>
            <div class="column is-four-fifths" style="font-size:2em;">
                <p>
                <h1 class="title is-1">{{ team.name }}</h1>
                <h6 class="subtitle is-6">{{team.game.name}}<br><a href="{{team.website}}">{{team.website}}</a></h6>
                {% ifequal ck_founder 1 %}
                <a href="{% url 'team:team_editinfo' team.pk %}"><button class="button" >Edit Info</button></a>
                {% endifequal %}
            </p>
            </div>
                
                <div class="column is-full notification">
                        <div class="column is-full">
                                <p><h4 class="title is-4">Bio</h2></p>
                               {{ team.description }}
                        </div>
                        
                        <div class="column is-full">
                                <p><h4 class="title is-4">Manager</h2></p>
                            <div class="columns">
                                    {% if team_manager %}
                                    {% for member in team_manager %}
                                <div class="column is-one-quarter">
                                    
                                        <figure class="image is-128x128">
                                            <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
                                        </figure>
                                        <a href="{% url 'member:player' member.member.pk %}">{{member.member.userprofile.codename}}</a>
                                </div>
                                {% endfor %}
                            {% else %}
                            <div class="column is-one-quarter"> 
                                    <p>None</p>
                            </div>
                            
                            {% endif %}
                            </div>
                        </div>
                        <div class="column is-full">
                                <p><h4 class="title is-4">Player</h2></p>
                                <div class="columns">
                                        {% if team_member %}
                                        {% for member in team_member %}
                                    <div class="column is-one-quarter">
                                            <center>
                                                    <a href="{% url 'member:player' member.member.pk %}"><figure class="image is-128x128">
                                                <img class="is-rounded" src="{{member.member.userprofile.profile_img.url}}">
                                            </figure>
                                            {{member.member.userprofile.codename}}
                                            <br>
                                            @{{member.member.username}}</a>
                                        </center>
                                    </div>
                                    {% endfor %}
                                {% else %}
                                None
                                {% endif %}
                                </div>
                            </div>
                </div>
                
        
            
        </div>
    <div>
            <!-- <p>Manager</p>
            <ul>
                {% if team_manager %}
                {% for member in team_manager %}
                <li>
                   <a href="{% url 'member:player' member.member.pk %}">{{member.member.userprofile.codename}}</a>
                </li>
                {% endfor %}
                {% else %}
                <li>None</li>
                {% endif %}
            </ul> -->
        <!-- <p>Player</p>
        <ul>
            {% for member in team_member %}
            <li>
                <a href="{% url 'member:player' member.member.pk %}">{{member.member.userprofile.codename}}</a>
            </li>
            {% endfor %}
        </ul> -->
    <!-- </div> -->
</div>

{% endblock %}

team/templates/team/team_list.html
<style type="text/css">
    .profile_lteam {
        width: 30px;
    }

    tr:hover {
        background-color: rgb(240, 240, 240);
    }

    th {
        color: white !important;
        background-color: rgb(75, 75, 75);
    }

    .text_search {
        margin-right: 10px;
    }
</style>
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% block body %}
{% load widget_tweaks %}
<div class="container">
    <br><br>
    <strong style="font-size:2em;">
        Find Team
    </strong>
    <br><br>
    <div>
        <form method="get">
                {% for field in filter.form %}
                    {{ field.label_tag }}
                    {{ field|add_class:"label input" }}
                {% endfor %}
                
                <button type="submit" class="button">Search</button>
        </form>
    </div>
    <br><br>
    <table class="table is-fullwidth">
        <tr>
            <th>Profile</th>
            <th>Name</th>
            <th>Games</th>
        </tr>
        {% for team in filter.qs %}
        <tr onclick="document.location = '/team/team_info/{{ team.pk }}/';">
            <td><img class="profile_lteam" src="{{ team.img.url }}" alt=""></td>
            <td>{{ team.name }}</td>
            <td><img class="profile_lteam" src="{{ team.game.img.url }}" alt="">{{team.game.name}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

team/templates/team/team_manage.html
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% block body %}

<div class="container"><br>
    <!-- logo team -->
    <img src="{% static 'img/profile/Microsoft.png' %}" alt="" width="100px;">
    <p>Team Name</p>
    <p>Bio of team</p>
    <div>
        <p>Game</p>
        <img src="{% static 'img/game/fifaonline4.png' %}" alt="" width="200px;">
    </div>

    <div>
        <p>Sponsor</p>
        <img src="{% static 'img/profile/google.jpg' %}" alt="" width="50px;">
        <!-- <img src="{% static 'img/profile/devteam_kik.jpg' %}" alt="" width="50px;">
        <img src="{% static 'img/profile/devteam_kong.jpg' %}" alt="" width="50px;"> -->
    </div>
    <a href="#"><button>Edit Team Info</button></a>

    <hr>
    <!-- Kong Section -->
    <div>
        <p>Register Form</p>
        <p>Form EX 1 <button>Edit</button> <button>Delete</button></p>
        <p>Form EX 2 <button>Edit</button> <button>Delete</button></p>
        <button>New Form</button>
    </div>
    <!-- End Kong Section -->
<hr>
    <div>
            <p>Member</p>
            <ul>
                <li>
                    Name 1 Ex Name <button>Delete</button>
                </li>
                <li>
                    Name 2 Ex Name <button>Delete</button>
                </li>
                <li>
                    Name 3 Ex Name <button>Delete</button>
                </li>
                <li>
                    Name 4 Ex Name <button>Delete</button>
                </li>
                <li>
                    Name 5 Ex Name <button>Delete</button>
                </li>
            </ul>
        </div>
</div>

{% endblock %}

team/templates/team/team_recruitment.html
<style type="text/css">
    .Heading{
        font-size: 2em !important;
    }
    .Heading2{
        font-size: 1.5em !important;
    }
</style>
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% block body %}

<div class="container">
    <br><br>

<div class="Heading">Fifa Online 4 กับทีมไอนีทโมจิ!</div>
<p class="Heading2">ทีม ไอนีทโมจิ</p>
<img src="#" alt="">
<br>
<p><strong> Description</strong></p>
<P>
    รับสมัครนักกีฬา E-Sports เกมส์ Fifa Online 4 กับทีมไอนีทโมจิ สนับสนุนโดย
    โมจิวัฒนพร
    <br>
    เงินเดือน : 9,000 บาท {{teamrc.id}}
</P>

ิ<br>
<p><strong>Start Date : </strong><div>10 August 2018</div></p>
<br>
<p><strong>End Date : </strong><div>20 November 2018</div></p>
</div>
{% endblock %}

team/templates/team/team_recruitment_create.html
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% block body %}
{% load widget_tweaks %}
<div class="container">
    <br><br>
    <form class="controls" method="POST">
        {% csrf_token %}
            {% for field in form %}
                {{ field.label_tag }}
                {{ field|add_class:"label input" }}
                {{ field.errors }}
            {% endfor %}
        
        <br><br>
        <div style="float:right;">
            <button class="button" type="submit">Create</button>
            <button class="button" type="reset">Clear</button>
        </div>
        {{text}}
    </form>
    <br><br><br><br>
</div><!-- Heading : <input class="input" type="text" name="heading"><br>
        Image Cover : <div class="file">
            <label class="file-label">
                <input class="file-input" type="file" name="resume">
                <span class="file-cta">
                    <span class="file-icon">
                        <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label">
                        Choose a file…
                    </span>
                </span>
            </label>
        </div>
        Description : <br> <textarea class="textarea" placeholder="Description" name="" id="" cols="30" rows="10"></textarea><br>
        Start-Date : <input class="input" type="date" name="" id="">
        End-Date : <input class="input" type="date" name="" id=""> -->

{% endblock %}

team/templates/team/team_recruitment_list.html
<style type="text/css">
    .profile_lteam {
        width: 30px;
    }

    tr:hover {
        background-color: rgb(240, 240, 240);
    }

    th {
        color: white !important;
        background-color: rgb(75, 75, 75);
    }

    .text_search {
        margin-right: 10px;
    }
</style>

{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block body %}

<div class="container">
    <!-- {% for TeamRecruitPost in posts %}
        {{TeamRecruitPost.heading}}
    {% endfor %} -->

    <br><br>
    <strong style="font-size:2em;">
        Recruitment Team
    </strong>
    <br><br>
    <div>
        <form class="controls" action="#">
            <p>Search</p>
            <input type="search" name="" id="" class="input" disabled>
            <br><br>
            <div class="columns">
                <!-- <div class="column is-2">
                    <div text_search>Game</div>
                    <div class="select">
                        <select>
                            <option>Overwatch</option>
                            <option>Fifa Online 4</option>
                            <option>ROV</option>
                            <option>Dota 2</option>
                        </select>
                    </div>
                </div> -->
                <div class="column is-2">
                    <div text_search>Game</div>
                    <div class="select">
                        <select disabled>
                            <option>Overwatch</option>
                            <option>Fifa Online 4</option>
                            <option>ROV</option>
                            <option>Dota 2</option>
                        </select>
                    </div>
                </div>
                <div class="column is-2">
                        <button class="button" type="submit" disabled>Search</button>
                </div>
                
            </div>
        </form>
    </div>
    <br><br>
    <table class="table is-fullwidth">
        <tr>
            <th>Team</th>
            <th>Heading</th>
            <th>Start Date</th>
            <th>End Date</th>
        </tr>
        {% for TeamRecruitPost in posts %}
        <tr>
            <td>{{ TeamRecruitPost.pk }}</td>
            <td>{{TeamRecruitPost.heading}}</td>
            <td>{{TeamRecruitPost.start_date}}</td>
            <td>{{TeamRecruitPost.end_date}}
                <button onclick="document.location = '{{ TeamRecruitPost.pk }}/';">Detail</button>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

team/templates/team/teami.html
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% block body %}
<div class="container"></div><br><br><br><br><center>
<div> Create your team with friends Create your team with friends Create your team with friends <br>
    Create your team with friends Create your team with friends Create your team with friends <br>
    <a href="{% url 'team:team_create' %}"><button class="button">Create Team</button></a> </div>
    <hr>
    <div> Create your team with friends Create your team with friends Create your team with friends <br>
        Create your team with friends Create your team with friends Create your team with friends <br>
        <a href="{% url 'team:team_list' %}"><button class="button">Find Team</button> </div>
</div></center>

{% endblock %}