esports_port_thailand/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('team/', include('team.urls')),
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout')
    # path('member/', include('django.contrib.auth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

member/urls.py
# from django.urls import path
from django.conf.urls import url , include
from django.urls import path
from . import views

app_name = 'member'
urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/post/<int:pk>/delete/',views.DeletePost.as_view(), name='delete_post'),
    path('player/<int:pk>/',views.Player.as_view(),name='player'),
    path('player/<int:pk>/follow/',views.Following.as_view(),name='following'),
    path('player/<int:pk>/unfollow/',views.Unfollow.as_view(),name='unfollow'),
    path('profile/',views.Profile.as_view(),name='profile'),
    path('profile/<int:pk>/edit/',views.EditProfile.as_view(),name='edit_profile'),
    path('mail/',views.MailBox.as_view(),name='mail'),
    path('mail/send/',views.SendMail.as_view(),name='send_mail'),
    path('mail/<int:pk>/',views.MailDetail.as_view(),name='mail_detail'),
    path('mail/<int:pk>/delete/',views.DeleteMail.as_view(),name='delete_mail'),
    path('search/',views.FilterUser.as_view(),name='member_search')
]

team/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = "team"
urlpatterns = [
    # path('signup/', views.SignUp.as_view(), name='signup'),
    # url(r'^$',views.index,name='index'),
    # url(r'^login$',views.login,name='login'),
    # url(r'^signup$',views.signup,name='signup'),
    path('', views.Teami.as_view(), name='teami'),
    path('team_info/<int:pk>/', views.TeamInfo.as_view(), name='team_info'),
    url(r'^team_create$', views.CreateTeam.as_view(), name='team_create'),
    url(r'^team_manage$', views.team_manage, name='team_manage'),
    path('team_info/<int:pk>/edit_info/', views.EditInfo.as_view(), name='team_editinfo'),
    url(r'^team_list$', views.team_list, name='team_list'),
    # url(r'^team_recruitment$', views.team_recruitment.as_view(), name='team_recruitment'),
    # url(r'^team_recruitment_list$', views.team_recruitment_list.as_view(), name='team_recruitment_list'),
    path('team_recruitment_list/',views.team_recruitment_list.as_view(),name='team_recruitment_list'),
    path('team_recruitment_list/<int:pk>/',views.team_recruitment.as_view(),name='team_recruitment'),
    url(r'^team_recruitment_create$', views.team_recruitment_create.as_view(), name='team_recruitment_create'),
    path('search/',views.FilterTeam.as_view(),name="team_search")
    # url(r'^profile$',views.profile,name='profile'),
    # path('home/',views.signup),
    # path('<code_name>/',views.profile)
]

member/models.py
from django.db import models
from django.contrib.auth.models import User

class Game(models.Model):
    name = models.CharField(max_length=20,primary_key=True)
    genre = models.CharField(max_length=20)
    img = models.ImageField(blank=True)
    def __str__(self):
        return self.name

class Country(models.Model):
    province = models.CharField(max_length=10,primary_key=True)
    counrty = models.CharField(max_length=10)
    def __str__(self):
        return self.province

class Role(models.Model):
    name = models.CharField(max_length=20,primary_key=True)
    duty = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class GameRole(models.Model):
    game_name = models.ForeignKey(Game,on_delete=models.CASCADE)
    role_name = models.ForeignKey(Role,on_delete=models.CASCADE)
    class Meta:
        unique_together = (("game_name","role_name"))

class Rank(models.Model):
    name = models.CharField(max_length=30,primary_key=True)
    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    codename = models.CharField(max_length=10,blank=True)
    streaming = models.CharField(max_length=30,blank=True)
    tel = models.CharField(max_length=10,blank=True)
    province = models.ForeignKey(Country,models.SET_NULL,blank=True,null=True)
    rank = models.ForeignKey(Rank,models.SET_NULL,blank=True,null=True)
    game = models.ForeignKey(Game,models.SET_NULL,blank=True,null=True)
    role = models.ForeignKey(Role,models.SET_NULL,blank=True,null=True)
    birtdate = models.DateField(null=True)
    profile_img = models.ImageField(default='default/default_profile.png',blank=True)
    cover_img = models.ImageField(default='default/default_cover.png', blank=True)
    

class Post(models.Model):
    poster = models.ForeignKey(User,on_delete=models.CASCADE)
    msg = models.CharField(max_length=1000)
    datetime = models.DateTimeField(auto_now_add=True)
    class Meta:
        unique_together = (("poster","datetime"))
    
class Mail(models.Model):
    sender = models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_requests_sender')
    reciever = models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_requests_reciever')
    topic = models.CharField(max_length=50)
    msg = models.CharField(max_length=300)
    datetime = models.DateTimeField(auto_now_add=True)
    class Meta:
        unique_together = (("sender", "reciever","datetime"))

class Follow(models.Model):
    follower = models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_requests_follower')
    following = models.ForeignKey(User,on_delete=models.CASCADE,related_name='%(class)s_requests_followed')
    date = models.DateField(auto_now_add=True)
    class Meta:
        unique_together = (("follower", "following"))

member/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile, Post, Mail

class MailForm(forms.ModelForm):
    to = forms.CharField(max_length =300)
    msg = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea'}))      
    reciever = forms.HiddenInput()
    class Meta:
        model = Mail
        fields = ['to','topic','msg']
        widgets = {
                'reciever': forms.HiddenInput(),
            }
        labels = {
           'to': 'Message to',
        }

    def save(self,commit=True):
        mail = super(MailForm, self).save(commit=False)
        user = User.objects.get(username=self.cleaned_data.get('to'))
        mail.reciever = user
        mail.msg = self.cleaned_data['msg']
        if commit:
            mail.save()
        return mail

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]
        help_texts={
            'username':'150 characters or fewer. Letters, digits and @/./+/-/_ only.',
            'password1':'Your password can\'t be too similar to your other personal information.<br>Your password must contain at least 8 characters.<br>Your password can\'t be a commonly used password.<br>Your password can\'t be entirely numeric.'
        }
    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        username = cleaned_data.get('username')
        if username and User.objects.filter(username__iexact=username).exists():
            self.add_error('username', 'A user with that username already exists.')
        return cleaned_data
    def save(self,commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.username = self.cleaned_data['username'].lower()
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user_profile = UserProfile()
        user_profile.user = user
        user_profile.pk = user.pk
        if commit:
            user.save()
            user_profile.save()
        
        return user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            'codename',
            'birtdate',
            'tel',
            'streaming',
            'province',
            'game',
            'role',
            'rank',
            'profile_img',
            'cover_img'
        ]
        widgets = {
            'birtdate': forms.DateInput(attrs={'type': 'date'}),
        }
    
        # widget = {'birtdate':forms.DateInput(attrs={'class':'datepicker'})}


class PostStatus(forms.ModelForm):
    msg = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Post
        fields = ['msg']
    # def save(self,commit=True):
    #     post = Post()
    #     post.poster = self.request.user
    #     post.
    #     if commit:
    #         post.save()

member/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from django.views import generic
from member.forms import RegistrationForm, PostStatus, ProfileForm, MailForm
from .models import UserProfile,Post,Follow,Mail
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from .filters import MemberFilter


class SignUp(generic.CreateView):
    form_class = RegistrationForm
    success_url = reverse_lazy('login')
    template_name = 'member/signup.html'

class Profile(generic.CreateView,LoginRequiredMixin,generic.ListView):
    form_class = PostStatus
    raise_exception = True
    context_object_name = "post_list"
    template_name = 'member/profile.html'
    success_url = reverse_lazy('member:profile')
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    model = User
    
    def get_context_data(self, **kwargs):
        context = super(Profile,self).get_context_data(**kwargs)
        context['post_list'] = Post.objects.filter(poster=self.request.user.pk)
        context['follower'] = Follow.objects.filter(following=self.request.user.pk)
        context['following'] = Follow.objects.filter(follower=self.request.user.pk)
        context['follower_len'] = len(Follow.objects.filter(following=self.request.user.pk))
        context['following_len'] = len(Follow.objects.filter(follower=self.request.user.pk))
        return context

    def get_queryset(self):
        post = Post.objects.filter(poster=self.request.user)[::-1]
        return post

    def form_valid(self, form):
        user = self.request.user
        form.instance.poster = user
        return super(Profile, self).form_valid(form)

class DeletePost(generic.DeleteView,LoginRequiredMixin):
    raise_exception = True
    model = Post
    success_url = reverse_lazy('member:profile')
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    def get(self, *args, **kwargs):
        """
        This has been overriden because by default
        DeleteView doesn't work with GET requests
        """
        return self.delete(*args, **kwargs)

class Player(generic.DetailView):
    template_name = 'member/player.html'
    model = User
    def get_context_data(self, **kwargs):
        context = super(Player,self).get_context_data(**kwargs)
        context['ck_follow'] = len(Follow.objects.filter(following=self.kwargs['pk'],follower=self.request.user.pk))
        context['follower'] = Follow.objects.filter(following=self.kwargs['pk'])
        context['following'] = Follow.objects.filter(follower=self.kwargs['pk'])
        context['post_list'] = Post.objects.filter(poster=self.kwargs['pk'])
        context['follower_len'] = len(Follow.objects.filter(following=self.kwargs['pk']))
        context['following_len'] = len(Follow.objects.filter(follower=self.kwargs['pk']))
        return context
    def dispatch(self,*args, **kwargs):
        if self.request.user.pk==self.kwargs['pk']:
            return redirect('member:profile')
        return super(Player, self).dispatch(*args, **kwargs)

class Following(generic.View):
    model = Follow

    def get_success_url(self, *arg, **kwargs):
        return reverse_lazy('member:player',kwargs={'pk': self.kwargs['pk']})

    def dispatch(self,*args, **kwargs):
        follow = Follow()
        follower = User.objects.get(pk=self.request.user.pk)
        following = User.objects.get(pk=self.kwargs['pk'])
        follow.follower = follower
        follow.following = following
        follow.save()
        # reverse_lazy('member:player',kwargs={'pk': self.kwargs['pk']})
        return HttpResponseRedirect(reverse_lazy('member:player',kwargs={'pk': self.kwargs['pk']}))

class Unfollow(generic.View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    def get_success_url(self, *arg, **kwargs):
        return reverse_lazy('member:player', kwargs={'pk': self.kwargs['pk']})
        
    def dispatch(self,*args, **kwargs):
        unfollow = Follow.objects.filter(follower=self.request.user.pk,following=self.kwargs['pk'])
        unfollow.delete()
        return HttpResponseRedirect(reverse_lazy('member:player', kwargs={'pk': self.kwargs['pk']}))

class MailBox(generic.ListView):
    model = Mail
    template_name = 'member/mail.html'
    def get_context_data(self, **kwargs):
        context = super(MailBox,self).get_context_data(**kwargs)
        context['mail_list'] = Mail.objects.filter(reciever=self.request.user)[::-1]
        return context
    

class SendMail(generic.CreateView):
    form_class = MailForm
    model = Mail
    template_name = 'member/send_mail.html'
    success_url = reverse_lazy('member:mail')
    def get_context_data(self, **kwargs):
        context = super(SendMail,self).get_context_data(**kwargs)
        context['reciever'] =  self.request.POST.get("reciever","")
        return context
    def form_valid(self, form):
        user = User.objects.get(pk=self.request.user.pk)
        form.instance.sender = user
        return super(SendMail, self).form_valid(form)

class Home(generic.ListView):
    template_name='member/home.html'
    context_object_name = "feed"
    def get_queryset(self):
        following = Follow.objects.filter(follower=self.request.user.pk)
        print(following)
        feed = Follow.objects.none()
        for i in following:
            temp = Post.objects.filter(poster=i.following.id)
            feed = feed | temp
        try:
            return feed.distinct().order_by('datetime')[::-1]
        except:
            return None

class EditProfile(generic.UpdateView):
    template_name = 'member/edit_profile.html'
    raise_exception = True
    model = UserProfile
    form_class = ProfileForm
    # fields = ['codename','birtdate','tel','streaming','province','game','role','rank','profile_img','cover_img']

    def get_success_url(self, *arg, **kwargs):
        return reverse('member:profile')

    def dispatch(self, *args, **kwargs):
        # user_profile = UserProfile.objects.get(pk=self.request.user.pk)
        if self.request.user.pk != self.kwargs['pk']:
            return redirect('member:profile')
        return super(EditProfile, self).dispatch(*args, **kwargs)


class MailDetail(generic.DetailView):
    template_name = 'member/mail_detail.html'
    model = Mail
    def get_context_data(self, **kwargs):
        context = super(MailDetail,self).get_context_data(**kwargs)
        context['mail_detail'] = Mail.objects.get(pk=self.kwargs['pk'])
        return context
    def dispatch(self,*args,**kwargs):
        mail = Mail.objects.get(pk=self.kwargs['pk'])
        if self.request.user.pk!=mail.reciever.pk:
            return redirect('member:mail')

        return super(MailDetail, self).dispatch(*args, **kwargs)

class DeleteMail(generic.DeleteView):
    raise_exception = True
    model = Mail
    success_url = reverse_lazy('member:mail')
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    def get(self, *args, **kwargs):
        return self.delete(*args, **kwargs)

class FilterUser(generic.ListView):
    model = UserProfile
    template_name = 'member/search_user.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = MemberFilter(self.request.GET,queryset=self.get_queryset())
        return context

member/templates/member/player.html
<style type="text/css">
    .profile {
        /* background-color: #f1e7e7; */
        padding: 70px 0px 30px 30px !important;
        color: #464646;
        background-color: #f0f0f0;

    }

    .columns {
        margin: 0px !important;
    }

    .column {

        padding: 0px !important;
    }

    .logo {
        width: 20px
    }

    .Heading_Profile {
        font-size: 1.3em;
    }

    body {
        background-color: #f0f0f0;
    }

    .post {
        background-color: #f7f7f7;
    }

    .status {
        background-color: #ebebeb;
        margin: 10px 0px 10px 0px !important;
    }

</style>
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load readmore %}
{% block body %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
    function modal1 () {
        $('#following').toggleClass('is-active');
    };
    function modal1Close(){
        $('#following').removeClass('is-active');
    }
    function modal2 () {
        $('#followers').toggleClass('is-active');
    };
    function modal2Close(){
        $('#followers').removeClass('is-active');
    }
</script>

<div id="following" class="modal">
        <div onclick="modal1Close.call(this)" class="modal-background"></div>
          <div class="modal-content">
                <div class="modal-card-body">
                {% for p in following %}
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-64x64">
                            <img src="{{p.following.userprofile.profile_img.url}}" alt="Image">
                        </figure>
                    </div>
                    <div class="media-content">
                        <div class="content">
                            <p>
                            <a href="{% url 'member:player' p.following.pk %}"><strong>{{p.following.first_name}} {{p.following.last_name}}</strong> <br><small>@{{p.following.username}}</small></a>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button onclick="modal1Close.call(this)" class="modal-close is-large" aria-label="close"></button>
        </div>
    </div>
<div id="followers" class="modal">
    <div onclick="modal2Close.call(this)" class="modal-background"></div>
      <div class="modal-content">
            <div class="modal-card-body">
            {% for p2 in follower %}
            <div class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <img src="{{p2.follower.userprofile.profile_img.url}}" alt="Image">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                        <a href="{% url 'member:player' p2.follower.pk %}"><strong>{{p2.follower.first_name}} {{p2.follower.last_name}}</strong> <br><small>@{{p2.follower.username}}</small></a>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <button onclick="modal2Close.call(this)" class="modal-close is-large" aria-label="close"></button>
    </div>
</div>

<div class="container" style="background-color:#f7f7f7">
    <div class="columns" >
        <div class="column is-3" >
        
            <div class="profile" style="background-color:#f7f7f7">
                    <nav class="level">
                            <div class="level-item has-text-centered">
                              <div>
                                <a onclick="modal1.call(this)"><p class="heading">Following</p>
                                <p class="title">{{following_len}}</p></a>
                              </div>
                            </div>
                            <div class="level-item has-text-centered">
                              <div>
                                <a onclick="modal2.call(this)"><p class="heading">Follower</p>
                                <p class="title">{{follower_len}}</p></a>
                              </div>
                            </div>
                          </nav>
                
                <center><img src="{{ user.userprofile.profile_img.url }}" style="width: 80%;" alt="">
                {% if ck_follow %}
                <a href="{% url 'member:unfollow' user.pk %}" class="button is-rounded">Unfollow</a>
                {% else %}
                <a href="{% url 'member:following' user.pk %}" class="button is-rounded">Follow</a>
                {% endif %}
                <form method="post" action="{% url 'member:send_mail' %}">
                    {% csrf_token %}
                    <input type="hidden" name="reciever" value="{{ user.username }}"></input>
                    <button type="submit" class="button" >Mail</button>
                </form>
                </center>
                <br>
                <p style="font-size:1.6em;margin-top: 20px;">
                        
                    {{user.first_name}} {{user.last_name}} ({{ user.userprofile.codename }})
                </p>
                <p>
                    @{{user.username}}
                </p><br>
                <!-- <p class="Heading_Profile">
                    Game
                </p> -->
                <p>
                    <img src="{{ user.userprofile.game.img.url }}" class="logo"> {{user.userprofile.game.name}}<br> [{{user.userprofile.rank}}]
                </p>
                <br>
                <p>Role: {{user.userprofile.role.name}}</p>
                <br>
                <div>
                    <!-- <p class="Heading_Profile">Live Stream</p> -->
                    <p><img class="logo" src="{% static 'img/logo/twitch.png' %}" alt=""><a href="http://www.twitch.com/{{user.userprofile.streaming}}">{{user.userprofile.streaming}}</a></p>
                </div>
                <br><br><br>
            </div>
        </div>
        <div class="column post">
            <img src="{{ user.userprofile.cover_img.url }}" width="100%" style="padding:10px;" alt="">
            <!-- post status input -->
            <!-- section -->
            {% for post in post_list %}
            <div class="columns status" style="padding:10px !important;">
                <div class="column is-1"><img src="{{ user.userprofile.profile_img.url }}" alt=""></div>
                <div class="column" style="padding:12px !important;">
                    <p><strong>{{post.poster.first_name}} {{post.poster.last_name}}</strong></p>
                    <p>{{ post.datetime}}</p>
                    <p>{{ post.msg|readmore:150 }}</p>
                

                </div>
            </div>
            {% endfor %}
            <!-- section -->
            
            <!-- section -->
        </div>
    </div>
</div>
{% endblock %}

member/templates/member/profile.html
<style type="text/css">
    .profile {
        /* background-color: #f1e7e7; */
        padding: 70px 0px 30px 30px !important;
        color: #464646;
        background-color: #f0f0f0;

    }

    .columns {
        margin: 0px !important;
    }

    .column {

        padding: 0px !important;
    }

    .logo {
        width: 20px
    }

    .Heading_Profile {
        font-size: 1.3em;
    }

    body {
        background-color: #f0f0f0;
    }

    .post {
        background-color: #f7f7f7;
    }

    .status {
        background-color: #ebebeb;
        margin: 10px 0px 10px 0px !important;
    }
</style>
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load readmore %}
{% block body %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
    function modal1 () {
        $('#following').toggleClass('is-active');
    };
    function modal1Close(){
        $('#following').removeClass('is-active');
    }
    function modal2 () {
        $('#followers').toggleClass('is-active');
    };
    function modal2Close(){
        $('#followers').removeClass('is-active');
    }
</script>
<div id="following" class="modal">
        <div class="modal-background" onclick="modal1Close.call(this)"></div>
          <div class="modal-content">
                <div class="modal-card-body">
                {% for p in following %}
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-64x64">
                            <img src="{{p.following.userprofile.profile_img.url}}" alt="Image">
                        </figure>
                    </div>
                    <div class="media-content">
                        <div class="content">
                            <p>
                            <a href="{% url 'member:player' p.following.pk %}"><strong>{{p.following.first_name}} {{p.following.last_name}}</strong> <br><small>@{{p.following.username}}</small></a>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button onclick="modal1Close.call(this)" class="modal-close is-large" aria-label="close"></button>
        </div>
    </div>
<div id="followers" class="modal">
    <div class="modal-background" onclick="modal2Close.call(this)"></div>
      <div class="modal-content">
            <div class="modal-card-body">
            {% for p in follower %}
            <div class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <img src="{{p.follower.userprofile.profile_img.url}}" alt="Image">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                        <a href="{% url 'member:player' p.follower.pk %}"><strong>{{p.follower.first_name}} {{p.follower.last_name}}</strong> <br><small>@{{p.follower.username}}</small></a>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <button onclick="modal2Close.call(this)" class="modal-close is-large" aria-label="close"></button>
    </div>
</div>


<div class="container" style="background-color:#f7f7f7">
    <div class="columns">
        <div class="column is-3">

            <div class="profile" style="background-color:#f7f7f7">
                    <nav class="level">
                            <div class="level-item has-text-centered">
                              <div>
                                <a onclick="modal1.call(this)"><p class="heading">Following</p>
                                <p class="title">{{following_len}}</p></a>
                                
                              </div>
                            </div>
                            <div class="level-item has-text-centered">
                              <div>
                                <a onclick="modal2.call(this)"><p class="heading">Follower</p>
                                <p class="title">{{follower_len}}</p></a>
                              </div>
                            </div>
                          </nav>
                <center>
                <img src="{{ request.user.userprofile.profile_img.url }}" style="width: 80%;" alt=""></center>
                <p style="font-size:1.6em;margin-top: 20px;">
                    {{request.user.first_name}} {{request.user.last_name}} ({{request.user.userprofile.codename}})
                </p>
                <p>
                    @{{request.user.username}}
                </p><br>
                <!-- <p class="Heading_Profile">
                    Game
                </p> -->
                <p>
                    <img src="{{ request.user.userprofile.game.img.url }}" class="logo"> {{request.user.userprofile.game.name}}<br> [{{request.user.userprofile.rank}}]
                </p>
                <p>Role: {{request.user.userprofile.role.name}}</p>
                <br>
                <div>
                    <!-- <p class="Heading_Profile">Live Stream</p> -->
                    <p><img class="logo" src="{% static 'img/logo/twitch.png' %}" alt=""><a href="http://www.twitch.com/{{request.user.userprofile.streaming}}"> {{request.user.userprofile.streaming}}</a></p>
                </div>
                <br><br><br>
            </div>
        </div>
        <div class="column post">
            <img src="{{ request.user.userprofile.cover_img.url }}" width="100%" style="padding:10px;" alt="">
            <!-- post status input -->
            <div>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        {{ field|add_class:"textarea post_input"|attr:"placeholder:What's up!"|attr:"rows:3" }}
                    {% endfor %}
                    <button type="submit" id="post" class="button is-info" style="float:right;">Post</button>
                </form>
            </div><br><br>
            <!-- section -->
            {% for post in post_list %}
            <div class="columns status" style="padding:10px !important;">
                <div class="column is-1"><img src="{{ request.user.userprofile.profile_img.url }}" alt=""></div>
                <div class="column" style="padding:12px !important;">
                    <p><strong>{{post.poster.first_name}} {{post.poster.last_name}}</strong></p>
                    <p>{{ post.datetime}}</p>
                    <p>{{ post.msg|readmore:150 }}</p>
                    <div style="float:right;">
                    <a href="{% url 'member:delete_post' post.pk %}"><button class="button is-danger">Delete</button></a></div>
                </div>
            </div>
            {% endfor %}
            <!-- section -->
            
            <!-- section -->
        </div>
    </div>
</div>
{% endblock %}