esports_port_thailand/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('team/', include('team.urls')),
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout')
    # path('member/', include('django.contrib.auth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

member/urls.py
# from django.urls import path
from django.conf.urls import url , include
from django.urls import path
from . import views

app_name = 'member'
urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/post/<int:pk>/delete/',views.DeletePost.as_view(), name='delete_post'),
    path('player/<int:pk>/',views.Player.as_view(),name='player'),
    path('player/<int:pk>/follow/',views.Following.as_view(),name='following'),
    path('player/<int:pk>/unfollow/',views.Unfollow.as_view(),name='unfollow'),
    path('profile/',views.Profile.as_view(),name='profile'),
    path('profile/<int:pk>/edit/',views.EditProfile.as_view(),name='edit_profile'),
    path('mail/',views.MailBox.as_view(),name='mail'),
    path('mail/send/',views.SendMail.as_view(),name='send_mail'),
    path('mail/<int:pk>/',views.MailDetail.as_view(),name='mail_detail'),
    path('mail/<int:pk>/delete/',views.DeleteMail.as_view(),name='delete_mail'),
    path('search/',views.FilterUser.as_view(),name='member_search')
]

team/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = "team"
urlpatterns = [
    # path('signup/', views.SignUp.as_view(), name='signup'),
    # url(r'^$',views.index,name='index'),
    # url(r'^login$',views.login,name='login'),
    # url(r'^signup$',views.signup,name='signup'),
    path('', views.Teami.as_view(), name='teami'),
    path('team_info/<int:pk>/', views.TeamInfo.as_view(), name='team_info'),
    url(r'^team_create$', views.CreateTeam.as_view(), name='team_create'),
    url(r'^team_manage$', views.team_manage, name='team_manage'),
    path('team_info/<int:pk>/edit_info/', views.EditInfo.as_view(), name='team_editinfo'),
    url(r'^team_list$', views.team_list, name='team_list'),
    # url(r'^team_recruitment$', views.team_recruitment.as_view(), name='team_recruitment'),
    # url(r'^team_recruitment_list$', views.team_recruitment_list.as_view(), name='team_recruitment_list'),
    path('team_recruitment_list/',views.team_recruitment_list.as_view(),name='team_recruitment_list'),
    path('team_recruitment_list/<int:pk>/',views.team_recruitment.as_view(),name='team_recruitment'),
    url(r'^team_recruitment_create$', views.team_recruitment_create.as_view(), name='team_recruitment_create'),
    path('search/',views.FilterTeam.as_view(),name="team_search")
    # url(r'^profile$',views.profile,name='profile'),
    # path('home/',views.signup),
    # path('<code_name>/',views.profile)
]

templates/base.html
<!DOCTYPE html>
<html>

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ESPTH</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <style type="text/css">
        .button.is-primary {
            background-color: #4d4d4d;
        }

        .navbar {
            background-color: #ebebeb;
        }
    </style>
</head>

<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'index' %}">
                <img src="{% static 'img/logo.png' %}" width="112" height="28">
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample"
                onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a href="{% url 'member:home' %}" class="navbar-item">
                    Home
                </a>
                <a href="{% url 'member:mail' %}" class="navbar-item">
                    Mail
                </a>
                <a href="{% url 'team:teami' %}" class="navbar-item">
                        Team
                    </a>
                <a href="{% url 'member:member_search' %}" class="navbar-item">
                    Search Player
                </a>
                <a href="{% url 'team:team_search' %}" class="navbar-item">
                        Search Team
                    </a>
            </div>

            <div class="navbar-end">
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        Profile
                    </a>

                    <div class="navbar-dropdown is-right">
                        <a class="navbar-item" href="{% url 'member:profile' %}">
                            <strong>{{request.user.first_name}} {{request.user.last_name}}</strong>
                        </a>
                        <a href="{% url 'member:edit_profile' request.user.pk %}" class="navbar-item">
                            Edit Profile
                        </a>

                        <!-- <a class="navbar-item">
                                    Jobs
                                </a>
                                <a class="navbar-item">
                                    Contact
                                </a> -->
                        <hr class="navbar-divider">
                        <a href="{% url 'logout' %}" class="navbar-item">
                            Log Out
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'lib/main.js' %}"></script>
    <script type="text/javascript" src="https://bulma.io/lib/index.js?v=201811050929"></script>

</body>

</html>

templates/base_public.html
<!DOCTYPE html>
<html>

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ESPTH</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <style type="text/css">
        .button.is-primary {
            background-color: #4d4d4d;
        }
        .button.is-primary:hover{
            background-color: #6b6b6b;
        }
        .navbar{
            background-color: #ebebeb;
        }
    </style>
</head>

<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'index' %}">
                <img src="{% static 'img/logo.png' %}" width="112" height="28">
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample"
                onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item">
                    Home
                </a>

                <a class="navbar-item">
                    About
                </a>

                <!-- <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        More
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item">
                            About
                        </a>
                        <a class="navbar-item">
                            Jobs
                        </a>
                        <a class="navbar-item">
                            Contact
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item">
                            Report an issue
                        </a>
                    </div>
                </div> -->
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary" href="{% url 'member:signup' %}">
                            <strong>Sign up</strong>
                        </a>
                        <a class="button is-light" href="{% url 'login' %}">
                            Log in
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'lib/main.js' %}"></script>
    <script type="text/javascript" src="https://bulma.io/lib/index.js?v=201811050929"></script>

</body>

</html>

templates/index.html
<style type="text/css">
.hero-body{background-image: url('https://g2e-gamers2mediasl.netdna-ssl.com/wp-content/uploads/2017/08/Rlwallpaper.jpg')}
</style>
{% extends user.is_authenticated|yesno:"base.html,base_public.html" %}

{% load staticfiles %}
{% block body %}
{% if user.is_authenticated %}
<script>
  window.location.replace("{% url 'member:home' %}");
</script>
{% endif %}
    <section class="hero is-medium is-primary">
      <div class="hero-body">
        <div class="container">
          <div class="columns">
            <div class="column is-8-desktop is-offset-2-desktop">
              <h1 class="title is-2 is-spaced">
                Hello Esport-Player!
              </h1>
              <h2 class="subtitle is-4">
                  Welcome to <strong>Esport Port Thailand</strong>
                  <br>Please Login or Sign Up
              </h2>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container">
        <div class="columns">
          <div class="column is-8-desktop is-offset-2-desktop">
            <div class="content">
             
          </div>
        </div>
      </div>
    </section>
    <footer class="footer has-text-centered">
      <div class="container">
         <div class="columns">
          <div class="column is-8-desktop is-offset-2-desktop">
            <p>
              <strong class="has-text-weight-semibold"> Copyrigth 2018 by
                ESPTH
              </strong>
            </p>
            <p>
              <small>
                Source code licensed <a href="http://opensource.org/licenses/mit-license.php">MIT</a>
              </small>
            </p>
            <p style="margin-top: 1rem;">
              <a href="http://bulma.io">
                <img src="{% static 'img/made-with-bulma.png' %}" alt="Made with Bulma" width="128" height="24">
              </a>
            </p>
          </div>
        </div>
      </div>
    </footer>
{% endblock %}